### PR TITLE
Update UR Driver submodule; add release note

### LINKED ISSUE #310: UR ROS2 Controller Driver file missing "realtime_box_best_effort.hpp"
Followed command as in pull [307](https://github.com/RobotecAI/ROSCon2023Demo/pull/307) (and also tried default command in README with added "--build-arg ROSCON_DEMO_BRANCH=development" as the default for branche "2.0.0" value didn't work)

Both commands ended with following exception:

In file included from /data/workspace/ROSCon2023Demo/ros2_ws/src/Universal_Robots_ROS2_Driver/ur_controllers/src/ur_configuration_controller.cpp:41:
879.2 /data/workspace/ROSCon2023Demo/ros2_ws/src/Universal_Robots_ROS2_Driver/ur_controllers/include/ur_controllers/ur_configuration_controller.hpp:50:10: fatal error: realtime_tools/realtime_box_best_effort.hpp: No such file or directory
879.2    50 | #include <realtime_tools/realtime_box_best_effort.hpp>
879.2       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I tracked the repository where the the file should be available but the file on the pinned commit isn't even there. 

Is the pinned commit incorrect?

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## What does this PR do?

Closes #310 

This PR is targeting the `main` branch and introducing a new patch release. This is caused by changes in ROS 2 API. The change will be backported to the development branch when accepted. The only change in this PR is an update of `Universal Robots ROS2 Driver` submodule (and information about it in the README). The project's version was bumped accordingly, the tag will be added after the PR is merged.

## How was this PR tested?

The ROS 2 workspace was built and the simulation was tested. UR moves as expected.

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
Note: the submodule was not updated to the newest version, as the newest version does not build correctly on the newest Ubuntu 22.04 (ROS 2 Humble) due to changes in ROS 2 API introduced after this branch was created.

**Review by arturkamieniecki — APPROVED** [review]
